### ISSUE TITLE
Leverage Git Hooks to automatically update the last_updated time variable

### ISSUE THREAD

**Issue by Bojak4616** [oasis-open/cti-documentation#45]
Use a `pre-push` [Git Hook](https://git-scm.com/book/th/v1/Customizing-Git-Git-Hooks) to automatically update https://github.com/oasis-open/cti-documentation/blob/master/_config.yml#L16 in make it near impossible for someone to forget to update the time.

**Comment by gtback** [comment]
It's possible if people don't install the hook 😉 (which as far as I can tell needs to run on user's client machines; we can't set up hooks that run on GitHub's servers). Nevertheless, I still think this is worth doing. The simplest approach may be to add a new commit for each push, but that could potentially add a ton of commits. It would be cool if you could amend the most recent commit, but I wonder if that makes thing too complex or introduces undesired behavior.

**Comment by SecurityDozo** [comment]
I'm not 100% sure how I'm going to tackle it yet, still kinda exploratory. My original thought was to keep the Git Hook in the repo so that when someone clones the repo they too will have the local functionality.

How often is code pushed? I was under the impression that most work is done locally then pushed once a few local commits have been made. But yes, this approach would bloat commits a bit. I'll look for cleaner approaches but having a slightly inflated number of commits on a repo doesn't that bad.

**Comment by gtback** [comment]
I personally only push when I think something is "done" (ready for a PR), or want someone else to review a work-in-progress, so it's probably not a big deal, but I wanted to be explicit about it.

**Comment by SecurityDozo** [comment]
After some digging it looks like the way to do this is with the library [pre-commit](http://pre-commit.com/). Git Hooks themselves cannot be committed with other code as part of a repo while also existing in `.git`.

**Comment by gtback** [comment]
Fixed by #46
